iStreamPlanet/github-actions

.github/CODEOWNERS

If we're going to start using this repository more, we're going to want more
control over what changes are going into it.

chore: Create a codeowners file

---

helmfile-actions/README.md
helmfile-actions/action.yml
helmfile-actions/apply.sh
helmfile-actions/diff.sh
helmfile-actions/main.sh

These are the scripts that ultimately make up a composite GitHub Action
for running helmfile while having status codes propagated in a more
intuitive way, on top of wrapping all of the edge cases for formatting
comment text back to a GH PR comment.

feat: Helmfile composite GitHub actions

---

.gitattributes

See https://github.com/github/linguist#using-gitattributes

chore: add gitattributes with linguist configuration

---

.github/CODEOWNERS

chore: Prep codeowners

---

helmfile-actions/action.yml
terraform-actions/action.yml

This should ammend #33 to actually bubble the output values up to the caller

fix(terraform/helmfile): use correct output names

---

helmfile-lock-stale/action.yml

- Correctly reference input variable

fix: Helmfile lock staleness input

---

helmfile-lock-stale/README.md

Need to touch the file to trigger a release so that #56 gets deployed

fix: update helmfile-lock-stale action

---

build-workspace-matrix/README.md

https://github.com/iStreamPlanet/github-actions/blob/main/build-workspace-matrix/action.yml#L7

docs(build-workspace-matrix): fix attribute name

---

.github/dependabot.yml
README.md
trufflehog-actions-scan/Dockerfile
trufflehog-actions-scan/action.yml
trufflehog-actions-scan/entrypoint.sh
trufflehog-actions-scan/requirements.txt

Based on https://github.com/edplato/trufflehog-actions-scan
* Uses requirement.txt so that Dependabot can provide updates.
* Sources regexes from the latest list.
* Uses a newer version of Trufflehog.

feat(trufflehog): add Trufflehog action.

---

.github/semantic.yml
.github/workflows/release.yml

* Support Dependabot `chore` PRs. 
* Change release trigger to be manual to avoid release churn when many dependency updates are merged in.

fix: Add configuration for the Release pipeline.

---

trufflehog-actions-scan/Dockerfile
trufflehog-actions-scan/requirements.txt

Use our forked version of Trufflehog with improvements.

feat: Using iStreamPlanet trufflehog.

---

helmfile-actions/apply.sh
helmfile-actions/diff.sh

Adding --suppress-secrets flag to prevent secrets from appearing in github actions
https://github.com/iStreamPlanet/github-actions/blob/d724b82091a68ce365e38e924da173389502fdec/helmfile-actions/apply.sh#L4
https://github.com/iStreamPlanet/github-actions/blob/d724b82091a68ce365e38e924da173389502fdec/helmfile-actions/diff.sh#L4

fix: suppressing helmfile secrets

---

helmfile-actions/apply.sh
helmfile-actions/diff.sh

This pull is just to update commit message to support a semantic release.

fix: suppress helm secrets in actions output

---

.github/CODEOWNERS

https://istreamplanet.atlassian.net/browse/IS-4278
Replacing individual code owner with SRE Team

chore: Replacing individual code owner with SRE Team

---

helmfile-actions/apply.sh
helmfile-actions/diff.sh
terraform-actions/apply.sh
terraform-actions/fmt.sh
terraform-actions/init.sh
terraform-actions/plan.sh
terraform-actions/validate.sh

This way we can observe the progress of the command without having to wait for it to finish.

feat: stream terraform/helmfile output to stdout

---

.github/stale.yml

chore: :wrench: add stalebot config

---

terraform-actions/main.sh

This reverts commit 1783e60c176018afea37ff2ba94f6fd7afb678ce.

fix: revert "Pass through arguments to terraform sub commands (#186)"

---

build-workspace-matrix/dist/index.js
build-workspace-matrix/main.ts
find-path-owners/dist/index.js
helmfile-dependency-check/dist/index.js
minimize-comments/dist/index.js
package.json
update-issue/dist/index.js
update-issue/main.ts

Transpile to unminimized output to make it easier to see what changed
Update some source to match API changes from actions/github 5.0

feat: rebuild node actions

---

build-workspace-matrix/README.md
build-workspace-matrix/__tests__/main.test.ts
build-workspace-matrix/action.yml
build-workspace-matrix/dist/index.js
build-workspace-matrix/main.ts

This change expands the syntax of the existing 'workspaces' argument instead of adding an extra argument

feat: alternative implementation for workspace dependencies

---

helmfile-actions/README.md
helmfile-actions/main.sh
helmfile-actions/sync.sh

- adding helmfile sync action to allow drift to be trued up

feat(helmfile-actions): Helmfile sync action

---

.github/workflows/lint-pr.yml
build-workspace-matrix/dist/index.js
find-path-owners/dist/index.js
helmfile-actions/diff.sh
helmfile-dependency-check/dist/index.js
minimize-comments/dist/index.js
package-lock.json
package.json
terraform-actions/plan.sh
update-issue/dist/index.js

- Set-output command is being deprecated in favor of using github enviroment files
- PR updates actions/core library and updates scripts to use github environment files

chore(con-372): updating deprecated set-output command

---

argocd-diff/action.yml
argocd-diff/main.sh

- creating reusable argocd-diff workflow

feat(con-423): Adding argocd-diff workflow

---

terraform-actions/README.md
terraform-actions/action.yml
terraform-actions/fmt.sh
terraform-actions/init.sh
terraform-actions/main.sh
terraform-actions/plan.sh
terraform-actions/validate.sh

Adding support for custom messages for all terraform actions that post a message to the GitHub PR.
See https://github.com/iStreamPlanet/con-eng-infra/pull/207 for an example output

feat: added support for a custom message to the terraform action output

---

helmfile-push-S3/README.md
helmfile-push-S3/action.yml

Adds a new custom github action to push helm charts to S3 to support Publishing

chore: add custom github action to push helm charts to S3

---

fail-alert.md

* fix link to slack keyword instructions
* add link to the actual thing the document is about 🤦

fix: Fix fail-alert readme
